/**
 * Drizzle ORM schema for Meavo Stock.
 *
 * Conventions:
 *  - All tables use snake_case in SQL, camelCase in TypeScript.
 *  - All `id` columns are UUID v4 generated by Postgres `gen_random_uuid()`.
 *  - JSON blobs use `jsonb` (efficient & queryable).
 *  - Timestamps are `timestamptz` to keep server-side TZ portable.
 */

import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

// ----------------------------- Enums -----------------------------

export const userRoleEnum = pgEnum("user_role", [
  "scanner",
  "reviewer",
  "admin",
]);

export const documentTypeEnum = pgEnum("document_type", [
  "invoice",
  "proforma",
  "delivery_note",
]);

export const documentStatusEnum = pgEnum("document_status", [
  "pending_review",
  "approved",
  "rejected",
  "synced",
  "sync_failed",
]);

export const deliveryZoneEnum = pgEnum("delivery_zone", [
  "local",
  "eu",
  "non_eu",
]);

export const syncAdapterEnum = pgEnum("sync_adapter", [
  "stub",
  "export",
  "api",
  "agent",
]);

export const syncStatusEnum = pgEnum("sync_status", [
  "queued",
  "running",
  "succeeded",
  "failed",
]);

// ----------------------------- Tables ----------------------------

/** App users — mirror of Supabase Auth users with our role attached. */
export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().notNull(), // matches auth.users.id
    email: text("email").notNull(),
    fullName: text("full_name"),
    avatarUrl: text("avatar_url"),
    role: userRoleEnum("role").default("scanner").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (t) => ({
    emailUq: uniqueIndex("users_email_uq").on(t.email),
  }),
);

/** Suppliers (counterparties) — created from extractions and curated by users. */
export const suppliers = pgTable(
  "suppliers",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`)
      .notNull(),
    name: text("name").notNull(),
    normalizedName: text("normalized_name").notNull(), // lowercased + trimmed for matching
    vatNumber: text("vat_number"),
    eik: text("eik"), // Bulgarian company identifier
    countryCode: text("country_code"), // ISO-3166-1 alpha-2
    address: text("address"),
    defaultCurrency: text("default_currency"), // ISO-4217 (e.g. BGN, EUR)
    deliveryZone: deliveryZoneEnum("delivery_zone"),
    zeronId: text("zeron_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (t) => ({
    normalizedIdx: index("suppliers_normalized_idx").on(t.normalizedName),
    vatIdx: index("suppliers_vat_idx").on(t.vatNumber),
    eikIdx: index("suppliers_eik_idx").on(t.eik),
  }),
);

/** Per-supplier extraction profile — drives few-shot learning. */
export const supplierExtractionProfiles = pgTable(
  "supplier_extraction_profiles",
  {
    supplierId: uuid("supplier_id")
      .primaryKey()
      .references(() => suppliers.id, { onDelete: "cascade" })
      .notNull(),
    /**
     * Free-form hints injected into the AI prompt.
     * Example: { "currency": "EUR", "vatTreatment": "reverse_charge", "notes": ["..."] }
     */
    hints: jsonb("hints").default(sql`'{}'::jsonb`).notNull(),
    /**
     * Recent approved extractions used as few-shot examples.
     * Capped at 5 entries (FIFO) by the learning logic.
     */
    recentExamples: jsonb("recent_examples")
      .default(sql`'[]'::jsonb`)
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
);

/** A scanned document (invoice / proforma / delivery note). */
export const documents = pgTable(
  "documents",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`)
      .notNull(),

    type: documentTypeEnum("type").notNull(),
    documentNumber: text("document_number"),
    issueDate: timestamp("issue_date", { mode: "date", withTimezone: false }),
    dueDate: timestamp("due_date", { mode: "date", withTimezone: false }),
    deliveryDate: timestamp("delivery_date", {
      mode: "date",
      withTimezone: false,
    }),

    supplierId: uuid("supplier_id").references(() => suppliers.id, {
      onDelete: "set null",
    }),
    // Snapshot of supplier text on the document (in case supplierId is null/unmatched)
    supplierNameRaw: text("supplier_name_raw"),

    currency: text("currency"),
    subtotal: numeric("subtotal", { precision: 18, scale: 4 }),
    vatTotal: numeric("vat_total", { precision: 18, scale: 4 }),
    total: numeric("total", { precision: 18, scale: 4 }),

    deliveryZone: deliveryZoneEnum("delivery_zone"),
    customsRef: text("customs_ref"), // MRN / МДД / МАД (only for non-EU)

    status: documentStatusEnum("status").default("pending_review").notNull(),

    originalFilePath: text("original_file_path").notNull(), // path in Supabase Storage `originals` bucket
    thumbnailPath: text("thumbnail_path"),
    originalMimeType: text("original_mime_type"),
    originalSizeBytes: bigint("original_size_bytes", { mode: "number" }),
    /** SHA-256 of the original bytes — used to dedupe re-uploads. */
    contentHash: text("content_hash"),

    /** Raw extraction returned by the AI provider (untouched). */
    rawAiExtraction: jsonb("raw_ai_extraction"),
    /** Confidence map: { "field.path": 0.0-1.0 }. */
    confidence: jsonb("confidence").default(sql`'{}'::jsonb`).notNull(),
    /** Final reviewed extraction (matches the zod schema after edits). */
    finalExtraction: jsonb("final_extraction"),

    extractorProvider: text("extractor_provider"), // e.g. "gemini-2.5-flash"

    zeronId: text("zeron_id"),
    syncedAt: timestamp("synced_at", { withTimezone: true }),

    createdBy: uuid("created_by").references(() => users.id, {
      onDelete: "set null",
    }),
    approvedBy: uuid("approved_by").references(() => users.id, {
      onDelete: "set null",
    }),
    approvedAt: timestamp("approved_at", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (t) => ({
    supplierIdx: index("documents_supplier_idx").on(t.supplierId),
    statusIdx: index("documents_status_idx").on(t.status),
    createdAtIdx: index("documents_created_at_idx").on(t.createdAt),
    contentHashIdx: index("documents_content_hash_idx").on(t.contentHash),
  }),
);

/** Line items extracted from a document. */
export const lineItems = pgTable(
  "line_items",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`)
      .notNull(),
    documentId: uuid("document_id")
      .references(() => documents.id, { onDelete: "cascade" })
      .notNull(),
    position: integer("position").notNull(), // 1-based row index
    sku: text("sku"),
    name: text("name").notNull(),
    quantity: numeric("quantity", { precision: 18, scale: 4 }),
    unit: text("unit"),
    unitPrice: numeric("unit_price", { precision: 18, scale: 4 }),
    vatRate: numeric("vat_rate", { precision: 6, scale: 3 }), // e.g. 20.000
    lineTotal: numeric("line_total", { precision: 18, scale: 4 }),
    matchedZeronItemId: text("matched_zeron_item_id"),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (t) => ({
    documentIdx: index("line_items_document_idx").on(t.documentId),
    documentPositionUq: uniqueIndex("line_items_doc_position_uq").on(
      t.documentId,
      t.position,
    ),
  }),
);

/** Every field-level edit a user makes vs the AI extraction — drives learning. */
export const correctionLogs = pgTable(
  "correction_logs",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`)
      .notNull(),
    documentId: uuid("document_id")
      .references(() => documents.id, { onDelete: "cascade" })
      .notNull(),
    supplierId: uuid("supplier_id").references(() => suppliers.id, {
      onDelete: "set null",
    }),
    /** dot+brackets path, e.g. "supplier.vatNumber" or "lineItems[2].unitPrice" */
    fieldPath: text("field_path").notNull(),
    aiValue: jsonb("ai_value"),
    userValue: jsonb("user_value"),
    /** Optional human note on why the change was made. */
    note: text("note"),
    correctedBy: uuid("corrected_by").references(() => users.id, {
      onDelete: "set null",
    }),
    correctedAt: timestamp("corrected_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (t) => ({
    documentIdx: index("correction_logs_document_idx").on(t.documentId),
    supplierFieldIdx: index("correction_logs_supplier_field_idx").on(
      t.supplierId,
      t.fieldPath,
    ),
  }),
);

/** Audit log of every Zeron sync attempt. */
export const syncAttempts = pgTable(
  "sync_attempts",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`)
      .notNull(),
    documentId: uuid("document_id")
      .references(() => documents.id, { onDelete: "cascade" })
      .notNull(),
    adapter: syncAdapterEnum("adapter").notNull(),
    status: syncStatusEnum("status").notNull(),
    /** Payload we attempted to send (for replay/debugging). */
    payload: jsonb("payload"),
    /** Response or output (XLSX path, API JSON, etc.). */
    response: jsonb("response"),
    error: text("error"),
    attemptedAt: timestamp("attempted_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    isCurrent: boolean("is_current").default(true).notNull(),
  },
  (t) => ({
    documentIdx: index("sync_attempts_document_idx").on(t.documentId),
    statusIdx: index("sync_attempts_status_idx").on(t.status),
  }),
);

// ----------------------------- Types -----------------------------

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Supplier = typeof suppliers.$inferSelect;
export type NewSupplier = typeof suppliers.$inferInsert;

export type SupplierExtractionProfile =
  typeof supplierExtractionProfiles.$inferSelect;
export type NewSupplierExtractionProfile =
  typeof supplierExtractionProfiles.$inferInsert;

export type DocumentRow = typeof documents.$inferSelect;
export type NewDocumentRow = typeof documents.$inferInsert;

export type LineItemRow = typeof lineItems.$inferSelect;
export type NewLineItemRow = typeof lineItems.$inferInsert;

export type CorrectionLog = typeof correctionLogs.$inferSelect;
export type NewCorrectionLog = typeof correctionLogs.$inferInsert;

export type SyncAttempt = typeof syncAttempts.$inferSelect;
export type NewSyncAttempt = typeof syncAttempts.$inferInsert;
